apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.1.10:6443
    token: {TOKEN}
    unsafeSkipCAVerification: true
  tlsBootstrapToken: {TOKEN}

nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: 
